// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: stock/v1/stock.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeductStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stock int64 `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
}

func (x *DeductStockRequest) Reset() {
	*x = DeductStockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_v1_stock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockRequest) ProtoMessage() {}

func (x *DeductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockRequest.ProtoReflect.Descriptor instead.
func (*DeductStockRequest) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{0}
}

func (x *DeductStockRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeductStockRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type IncreaseStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stock int64 `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
}

func (x *IncreaseStockRequest) Reset() {
	*x = IncreaseStockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_v1_stock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncreaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStockRequest) ProtoMessage() {}

func (x *IncreaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStockRequest.ProtoReflect.Descriptor instead.
func (*IncreaseStockRequest) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{1}
}

func (x *IncreaseStockRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IncreaseStockRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type DeductIntegralRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Integral int64 `protobuf:"varint,2,opt,name=Integral,proto3" json:"Integral,omitempty"`
}

func (x *DeductIntegralRequest) Reset() {
	*x = DeductIntegralRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_v1_stock_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeductIntegralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductIntegralRequest) ProtoMessage() {}

func (x *DeductIntegralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductIntegralRequest.ProtoReflect.Descriptor instead.
func (*DeductIntegralRequest) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{2}
}

func (x *DeductIntegralRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeductIntegralRequest) GetIntegral() int64 {
	if x != nil {
		return x.Integral
	}
	return 0
}

type IncreaseIntegralRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Integral int64 `protobuf:"varint,2,opt,name=Integral,proto3" json:"Integral,omitempty"`
}

func (x *IncreaseIntegralRequest) Reset() {
	*x = IncreaseIntegralRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_v1_stock_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncreaseIntegralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseIntegralRequest) ProtoMessage() {}

func (x *IncreaseIntegralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseIntegralRequest.ProtoReflect.Descriptor instead.
func (*IncreaseIntegralRequest) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{3}
}

func (x *IncreaseIntegralRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IncreaseIntegralRequest) GetIntegral() int64 {
	if x != nil {
		return x.Integral
	}
	return 0
}

var File_stock_v1_stock_proto protoreflect.FileDescriptor

var file_stock_v1_stock_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3a, 0x0a, 0x12, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x3c, 0x0a,
	0x14, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x43, 0x0a, 0x15, 0x44,
	0x65, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c,
	0x22, 0x45, 0x0a, 0x17, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x32, 0xbf, 0x02, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x12, 0x47, 0x0a, 0x0b, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4b, 0x0a, 0x0d, 0x49, 0x6e,
	0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x22, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x63, 0x72, 0x65,
	0x61, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4d, 0x0a, 0x0e, 0x44, 0x65, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x51, 0x0a, 0x10, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61,
	0x73, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61,
	0x73, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x2b, 0x0a, 0x0c, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x19, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stock_v1_stock_proto_rawDescOnce sync.Once
	file_stock_v1_stock_proto_rawDescData = file_stock_v1_stock_proto_rawDesc
)

func file_stock_v1_stock_proto_rawDescGZIP() []byte {
	file_stock_v1_stock_proto_rawDescOnce.Do(func() {
		file_stock_v1_stock_proto_rawDescData = protoimpl.X.CompressGZIP(file_stock_v1_stock_proto_rawDescData)
	})
	return file_stock_v1_stock_proto_rawDescData
}

var file_stock_v1_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stock_v1_stock_proto_goTypes = []interface{}{
	(*DeductStockRequest)(nil),      // 0: api.stock.v1.DeductStockRequest
	(*IncreaseStockRequest)(nil),    // 1: api.stock.v1.IncreaseStockRequest
	(*DeductIntegralRequest)(nil),   // 2: api.stock.v1.DeductIntegralRequest
	(*IncreaseIntegralRequest)(nil), // 3: api.stock.v1.IncreaseIntegralRequest
	(*emptypb.Empty)(nil),           // 4: google.protobuf.Empty
}
var file_stock_v1_stock_proto_depIdxs = []int32{
	0, // 0: api.stock.v1.Stock.DeductStock:input_type -> api.stock.v1.DeductStockRequest
	1, // 1: api.stock.v1.Stock.IncreaseStock:input_type -> api.stock.v1.IncreaseStockRequest
	2, // 2: api.stock.v1.Stock.DeductIntegral:input_type -> api.stock.v1.DeductIntegralRequest
	3, // 3: api.stock.v1.Stock.IncreaseIntegral:input_type -> api.stock.v1.IncreaseIntegralRequest
	4, // 4: api.stock.v1.Stock.DeductStock:output_type -> google.protobuf.Empty
	4, // 5: api.stock.v1.Stock.IncreaseStock:output_type -> google.protobuf.Empty
	4, // 6: api.stock.v1.Stock.DeductIntegral:output_type -> google.protobuf.Empty
	4, // 7: api.stock.v1.Stock.IncreaseIntegral:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stock_v1_stock_proto_init() }
func file_stock_v1_stock_proto_init() {
	if File_stock_v1_stock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stock_v1_stock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeductStockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_v1_stock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncreaseStockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_v1_stock_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeductIntegralRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_v1_stock_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncreaseIntegralRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stock_v1_stock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_v1_stock_proto_goTypes,
		DependencyIndexes: file_stock_v1_stock_proto_depIdxs,
		MessageInfos:      file_stock_v1_stock_proto_msgTypes,
	}.Build()
	File_stock_v1_stock_proto = out.File
	file_stock_v1_stock_proto_rawDesc = nil
	file_stock_v1_stock_proto_goTypes = nil
	file_stock_v1_stock_proto_depIdxs = nil
}
