swagger: "2.0"
info:
  title: hello-kratos
  version: "1.0"
tags:
  - name: Greeter
  - name: Stock
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /helloworld/{name}:
    get:
      summary: helloword
      operationId: Greeter_SayHello
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1HelloReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: name
          description: 名称
          in: path
          required: true
          type: string
      tags:
        - hello-kratos
  /stock/add:
    post:
      summary: 增加库存
      operationId: Greeter_AddStock
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1IncreaseStockRequest'
      tags:
        - stock
  /stock/deduct:
    post:
      summary: 扣库存
      operationId: Greeter_DeductStock
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1DeductStockRequest'
      tags:
        - stock
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1DeductStockRequest:
    type: object
    properties:
      id:
        type: string
        format: int64
      stock:
        type: string
        format: int64
  v1HelloReply:
    type: object
    properties:
      message:
        type: string
    title: The response message containing the greetings
  v1IncreaseStockRequest:
    type: object
    properties:
      id:
        type: string
        format: int64
      stock:
        type: string
        format: int64
securityDefinitions:
  TokenAuth:
    type: apiKey
    description: '用户认证,格式为: Bearer+空格+token'
    name: Authorization
    in: header
